excel_rename_dictionary = \
    {
        'vehicle_status': 'Vehicle Status',
        'customer_group': 'Customer Group',
        'relationship_manager': 'Account Manager',
        'vehicle_type': 'Vehicle Type',
        'registration': 'Registration',
        'hire_expiry_date': 'Hire End Date',
        'customer_status': 'Customer Status',
        'in_scope': 'In Scope?',
        'engagement_level': 'Engagement Level',
        'current_view': 'Current View',
        'expected_return_date': 'Expected Return Date',
        'second_decision': '2nd Decision',
        'expected_return_date_2': 'Expected Return Date',
        'plan_view': 'Plan View',
        'product_manager_view': 'Product Manager View',
        'product_manager_return_date': 'Product Manager Return Date',
        'mileage_banding': 'Mileage Banding',
        'up_priced': 'Up Priced',
        'latest_increase': 'Latest Increase',
        'effective_date': 'Effective Date',
        'customer_acc_number': 'Customer Account Number',
        'customer_name': 'Customer Name',
        'segment': 'Segment',
        'hexagon_powered_fleet': 'Hexagon Powered Fleet',
        'hexagon_trailer_fleet': 'Hexagon Trailer Fleet',
        'hexagon_ancillary_fleet': 'Hexagon Ancillary Fleet',
        'hexagon_undefined_fleet': 'Hexagon Undefined Fleet',
        'total_customer_fleet': 'Total Hexagon Fleet',
        'power_type': 'Power Type',
        'vehicle_on_fleet_date': 'Vehicle On Fleet Date',
        'years_in_service': 'Years In Service',
        'manufacturer': 'Manufacturer',
        'model': 'Model',
        'parent_type': 'Parent vehicle Type',
        'fridge': 'Fridge?',
        'supplier_name': 'Supplier name',
        'supplier_post_code': 'Supplier Post Code',
        'mileage': 'Current Mileage',
        'mileage_date': 'Mileage Reading Date',
        'daily_mileage': 'Daily Mileage',
        'projected_end_mileage': 'Project Mileage At Contract End',
        'contract_annual_mileage': 'Contract Annual Mileage Allowance',
        'rated_mileage_at_reading_date': 'Rated Mileage @ Reading Date',
        'over_under_rated_mileage_number': 'Over/Under Rated Mileage @ Reading Date',
        'over_under_rated_mileage_percentage': 'Over/Under Rated Mileage % @ Reading Date',
        'financer': 'Financer',
        'capital': 'Capital',
        'net_book_value': 'NBV',
        'residual_value': 'Residual',
        'finance_end_date': 'Finance End Date',
        'monthly_depreciation': 'Monthly Depreciation',
        'hire_start_date': 'Hire Start Date',
        'original_hire_date': 'Original Hire Start Date',
        'Contract_Billing_Amount_Monthly': 'Contract Billing Amount(Monthly)',
        'Contract_Billing_Amount_Annually': 'Contract Billing Amount(Annually)',
        'Contract_Billing_Amount_Weekly': 'Contract Billing Amount(Weekly)',
        'billing_frequency': 'Billing Frequency',
        'Current_Contract_Expiry_Month': 'Current Contract Expiry Month',
        'Current_Contract_Expiry_Year': 'Current Contract Expiry Year',
        'contract_status': 'Contract Status',
        '3_month_revenue': '3 Month Revenue',
        '3_month_spend': '3 Month Expenditure',
        '3_month_margin': '3 Month Margin',
        '3_month_margin_%': '3 Month Margin %',
        '12_month_revenue': '12 Month Revenue',
        '12_month_spend': '12 Month Expenditure',
        '12_month_margin': '12 Month Margin',
        '12_month_margin_%': '12 Month Margin %',
        'life_revenue': 'Life Revenue',
        'life_spend': 'Life Expenditure',
        'life_margin': 'Life Margin',
        'life_margin_%': 'Life Margin %',
        'registration_2': 'Registration 2',
        'vehicle_type_2': 'Vehicle Type 2',
        'hire_expiry_date_2': 'Hire End Date 2',
        '3_month_finance': '3 Month Finance',
        '12_month_finance': '12 Month Finance',
        'life_finance': 'Life Finance',
        '3_month_rfl': '3 Month RFL',
        '12_month_rfl': '12 Month RFL',
        'life_rfl': 'Life RFL',
    }